/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // shadcn/ui tokens (kept for component compat)
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Emerald Executive design system
        primary: {
          DEFAULT: "#003527",
          container: "#064e3b",
          fixed: "#b0f0d6",
          "fixed-dim": "#95d3ba",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#006c49",
          container: "#6cf8bb",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
          foreground: "#ffffff",
        },
        tertiary: {
          DEFAULT: "#581800",
          container: "#7e2600",
          fixed: "#ffdbcf",
          "fixed-dim": "#ffb59c",
          foreground: "#ffffff",
        },
        surface: {
          DEFAULT: "#f9f9ff",
          dim: "#d3daef",
          bright: "#f9f9ff",
          "container-lowest": "#ffffff",
          "container-low": "#f1f3ff",
          container: "#e9edff",
          "container-high": "#e1e8fd",
          "container-highest": "#dce2f7",
          tint: "#2b6954",
          variant: "#dce2f7",
          "off-white": "#F9FAF7",
          cream: "#F5F1E8",
        },
        "on-surface": "#141b2b",
        "on-surface-variant": "#404944",
        "inverse-surface": "#293040",
        "inverse-on-surface": "#edf0ff",
        "inverse-primary": "#95d3ba",
        "on-primary": "#ffffff",
        "on-primary-container": "#80bea6",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#0b513d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ff9671",
        "on-tertiary-fixed": "#380c00",
        "on-tertiary-fixed-variant": "#822800",
        outline: "#707974",
        "outline-variant": "#bfc9c3",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "accent-coral": { DEFAULT: "#FF7F50", hover: "#e56a3a" },
        "success-emerald": "#059669",
        // Post-type semantic colors (still used in UI for "need" post type indicator)
        need: { DEFAULT: "#006c49", light: "#dcfce7" },
        // shadcn accent token
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        headline: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
      borderRadius: {
        '2xl': '16px',
        xl: "12px",
        lg: "8px",
        md: "6px",
        sm: "4px",
        xs: "2px",
        full: "9999px",
      },
      spacing: {
        "stack-gap-lg": "32px",
        "stack-gap-md": "16px",
        "stack-gap-sm": "8px",
        "margin-desktop": "48px",
        "margin-mobile": "20px",
        "gutter-desktop": "24px",
        "gutter-mobile": "16px",
        "container-max-width": "1280px",
      },
      maxWidth: {
        "container-max-width": "1280px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: "0 4px 20px 0 rgba(6,78,59,0.05)",
        "card-hover": "0 12px 32px 0 rgba(6,78,59,0.12)",
        "card-emerald": "0 4px 0 #064e3b",
        float: "0 12px 24px rgba(6,78,59,0.10)",
        "nav": "0 4px 20px 0 rgba(6,78,59,0.05)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "pulse-skeleton": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "pulse-emerald": {
          "0%": { boxShadow: "0 0 0 0 rgba(0, 53, 39, 0.4)" },
          "70%": { boxShadow: "0 0 0 10px rgba(0, 53, 39, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(0, 53, 39, 0)" },
        },
        "float-ambient": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "reveal-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(6px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        marquee: "marquee 30s linear infinite",
        "pulse-skeleton": "pulse-skeleton 1.5s ease-in-out infinite",
        "pulse-emerald": "pulse-emerald 2s infinite",
        "float-ambient": "float-ambient 4s ease-in-out infinite",
        "reveal-up": "reveal-up 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "bounce-subtle": "bounce-subtle 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
